# Generated by Django 4.2.11 on 2024-03-12 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text',
        ),
        migrations.AddField(
            model_name='question',
            name='choice_1',
            field=models.CharField(default='Choice 1', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_2',
            field=models.CharField(default='Choice 2', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_3',
            field=models.CharField(default='Choice 3', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='choice_4',
            field=models.CharField(default='Choice 4', max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_choice',
            field=models.CharField(choices=[('choice_1', 'Choice 1'), ('choice_2', 'Choice 2'), ('choice_3', 'Choice 3'), ('choice_4', 'Choice 4')], default='Choice 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200),
        ),
    ]
