# Generated by Django 4.2.11 on 2024-03-13 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0002_remove_question_answer_text_question_choice_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='choice_1',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_2',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_3',
        ),
        migrations.RemoveField(
            model_name='question',
            name='choice_4',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=100)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='toefl_prep_app.question')),
            ],
        ),
    ]
