# Generated by Django 4.2.11 on 2024-03-13 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0003_remove_question_choice_1_remove_question_choice_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_choice',
            field=models.PositiveIntegerField(choices=[(1, 'Choice 1'), (2, 'Choice 2'), (3, 'Choice 3'), (4, 'Choice 4')], default=0),
        ),
    ]
