# Generated by Django 4.2.11 on 2024-03-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0005_remove_choice_question_alter_question_correct_choice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_choice',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='toefl_prep_app.choice'),
        ),
    ]
