# Generated by Django 4.2.11 on 2024-03-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0006_alter_question_correct_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=0),
        ),
    ]
