# Generated by Django 4.2.11 on 2024-03-13 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0007_choice_question_number_question_question_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question_number',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_choice',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_number',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='toefl_prep_app.question'),
        ),
    ]
