# Generated by Django 4.2.11 on 2024-03-13 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0008_remove_choice_question_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='toefl_prep_app.question'),
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toefl_prep_app.choice')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='toefl_prep_app.question')),
            ],
        ),
    ]
