# Generated by Django 4.2.11 on 2024-03-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0009_alter_choice_question_correctanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='audio/'),
        ),
    ]
