# Generated by Django 4.2.11 on 2024-03-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toefl_prep_app', '0010_question_audio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test_attempted',
            field=models.BooleanField(default=False),
        ),
    ]
